import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Menu from '../components/Menu/Menu';
import Portfolio from '../components/Portfolio/Portfolio';

import { apiToken } from '../components/auth';
import { getProjects } from './api/projects';

export async function getStaticProps() {
  const token = await apiToken();
  const projects = await getProjects(token);

  return {
    props: {
      projects,
      test: 'It works!'
    }
  }
}

export default function Home({ projects, test }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Menu />
        <Portfolio />
        { test }
      </main>
    </div>
  )
}
